sudo: required
services:
    - docker
    
before_install:
    - docker build -t sdidassou/docker-react -f Dockerfile.dev .
    
script:
    - docker run sdidassou/docker-react npm run test -- --coverage